---
- name: Schedule Future Jobs
  hosts: node1
  become: true
  tasks:
    - name: Schedule a command to execute in 1 minutes as root
      ansible.posix.at:
        command: lsblk > /tmp/lsblk.txt
        count: 1
        units: minutes
...
