---
- name: Schedule Future Jobs
  hosts: node1
  become: true
  tasks:
    - name: Schedule a command to execute in 3 days as root
      ansible.posix.at:
        command: uptime > /tmp/uptime.txt
        count: 3
        units: days
...

