---
- name: Schedule Future Jobs
  hosts: node1
  become: true
  tasks:
    - name: Removes a cron file from under /etc/cron.d
      ansible.builtin.cron:
        name: yum autoupdate
        cron_file: ansible_yum-autoupdate
        state: absent
...
