---
- name: iSCSI Target Server Configuration Playbook
  hosts: node1
  become: true
  tasks:
    - name: Run the iscsi-target script which does not exists on the remote node.
      script: /home/vikasnehra/iscsi-target.sh
      args:
        creates: /home/vikasnehra/iscsi-target.sh
...
