---
- name: Yum Repository Management
  hosts: node1
  become: true
  tasks:
    - name: Install the nginx rpm from a remote repo
      yum:
        name: http://nginx.org/packages/centos/6/noarch/RPMS/nginx-release-centos-6-0.el6.ngx.noarch.rpm
        state: present
        disable_gpg_check: true
...
