---
- name: Yum Repository Management
  hosts: node1
  become: true
  tasks:
    - name: Add multiple repositories into the same file
      yum_repository:
         name: epel2
         description: EPEL YUM repo
         file: external_repos
         baseurl: https://download.fedoraproject.org/pub/epel/$releasever/$basearch/
         gpgcheck: no
...
