---
- name: managing the file permissions using ansible.
  hosts: node1
  become: true
  tasks:
    - name: Update modification and access time of given file
      file:
        path: /etc/linux
        state: directory
        modification_time: now
        access_time: now
...
