---
- name: managing the file permissions using ansible.
  hosts: node1
  become: true
  tasks:
    - name: Touch again the same file, but do not change times this makes the task idempotent
      file:
        path: /etc/linux.conf
        state: touch
        mode: u+rw,g-wx,o-rwx
...
