---
- name: managing the file permissions using ansible.
  hosts: node1
  become: true
  tasks:
    - name: Create hard link
      file:
        src: '/etc/redhat-release'
        dest: '/tmp/hardlink'
        state: hard
...
