---
- name: managing the file permissions using ansible.
  hosts: node1
  become: true
  tasks:
    - name: Create a symbolic link
      file:
        src: /etc/redhat-release
        dest: /tmp/link
        owner: vikasnehra
        group: vikasnehra
        state: link
...
