---
- name: process management using ansible playbook
  hosts: node1
  become: yes
  tasks:
    - name: installing the httpd packages on the managed node
      yum:
        name: httpd
        state: latest

    - name: starting the httpd service on the managed node
      service:
        name: httpd
        state: started
  
    - name: Get running processes list from remote host
      ignore_errors: yes
      shell: "ps -few | grep httpd | awk '{print $2}'"
      register: running_processes

    - name: Printing the process IDs of the httpd processes
      debug:
        msg: "{{ running_processes }}"
...
