---
- name: Managing Storage Space Using Ansible
  hosts: node1
  become: true
  tasks:
    - name: Create a new primary partition with a size of 1GiB
      parted:
        device: /dev/sda
        number: 1
        state: present
        part_end: 1GiB
...
