---
- name: Managing Volume Groups
  hosts: node1
  become: true
  tasks:
    - name: Create a logical volume of 512m
      community.general.lvol:
        vg: nehraclasses
        lv: test
        size: 512
...

