---
- name: Managing Volume Groups
  hosts: node1
  become: true
  tasks:
    - name: Create a snapshot volume of the test logical volume.
      community.general.lvol:
        vg: nehraclasses
        lv: test
        snapshot: snap1
        size: 100m
...

