---
- name: Managing Volume Groups
  hosts: node1
  become: true
  tasks:
    - name: Reduce the logical volume by given space
      community.general.lvol:
        vg: nehraclasses
        lv: test
        size: -512M
        force: true
...

