---
- name: Managing Volume Groups
  hosts: node1
  become: true
  tasks:
     - name: Extend the logical volume to 1024m.
       community.general.lvol:
         vg: nehraclasses
         lv: test
         size: 1024
...

