---
- name: Managing Volume Groups
  hosts: node1
  become: true
  tasks:
     - name: Extend the logical volume to consume all remaining space in the volume group
       community.general.lvol:
         vg: nehraclasses
         lv: test
         size: +100%FREE
...

