---
- name: Managing Volume Groups
  hosts: node1
  become: true
  tasks:
     - name: Reduce the logical volume to 512m
       community.general.lvol:
         vg: nehraclasses
         lv: test
         size: 512
         force: true
...
