---
- name: Managing Volume Groups
  hosts: node1
  become: true
  tasks:
    - name: Create a volume group on top of /dev/sda1 with physical extent size = 32MB
      community.general.lvg:
        vg: nehraclasses
        pvs: /dev/sda1
        pesize: 32
...
